# Generated by Django 3.2.4 on 2022-10-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='employee_name',
            field=models.CharField(default='-', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examplemodel',
            name='topic',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
